/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#003c90',
        'on-primary': '#ffffff',
        'primary-container': '#0f52ba',
        'on-primary-container': '#bcceff',
        'secondary': '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'tertiary': '#5c3800',
        'tertiary-container': '#7c4d00',
        'on-tertiary-container': '#ffc278',
        'surface': '#f8f9ff',
        'surface-container': '#e5eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#434653',
        'outline': '#737784',
        'outline-variant': '#c3c6d5',
        'error': '#ba1a1a',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'surface-tint': '#1d59c1',
        'surface-dim': '#cbdbf5',
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      fontFamily: {
        'heading': ['Hanken Grotesk', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      boxShadow: {
        'elevation-1': '0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px 0 rgba(0,0,0,0.06)',
        'elevation-2': '0px 10px 15px -3px rgba(15, 82, 186, 0.08)',
      },
    },
  },
  plugins: [],
};